# Use postgres/example user/password credentials
version: '3.1'

services:

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=test123
    restart: always
    ports:
      - 3306:3306
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - mysql
    environment:
     - PMA_ARBITRARY=1
    restart: always
    external_links:
        - db_server:db
    ports:
      - 8080:80
